export const gamesArray = [
    {
        name: "Ping pong championship",
        description: "Ping Pong Championship, a ping pong simulator",
        id: "1",
        image: "../images/GameHub_covers.jpg",
        price: "$ 29.99",
        oldPrice: "",
        popular: true,
        preOrder: false,
        used: true,
    },
    {
        name: "Super Duper",
        description: "Super Duper, a dancing simulator",
        id: "2",
        image: "../images/GameHub_covers2.jpg",
        price: "$ 35.99",
        oldPrice: "$ 59.99",
        popular: false,
        preOrder: false,
        used: false,
    },
    {
        name: "Black",
        description: "Black, a horror game not for the faint hearted",
        id: "3",
        image: "../images/GameHub_covers3.jpg",
        price: "$ 6.66",
        oldPrice: "",
        popular: true,
        preOrder: false,
        used: true,
    },
    {
        name: "Furious",
        description: "Furious, a PvP fighting game",
        id: "4",
        image: "../images/GameHub_covers4.jpg",
        price: "$ 20.00",
        oldPrice: "$ 39.99",
        popular: false,
        preOrder: false,
        used: false,
    },
    {
        name: "Assassin",
        description: "Assassin, a stealth base game",
        id: "5",
        image: "../images/GameHub_covers5.jpg",
        price: "$ 41.99",
        oldPrice: "$ 59.99",
        popular: false,
        preOrder: false,
        used: false,
    },
    {
        name: "Space War",
        description: "Space war, the closest thing you'll get to star wars",
        id: "6",
        image: "../images/GameHub_covers6.jpg",
        price: "$ 29.99",
        oldPrice: "",
        popular: false,
        preOrder: false,
        used: true,
    },
    {
        name: "Racing",
        description: "Racing, a formel 1 racing game",
        id: "7",
        image: "../images/GameHub_covers7.jpg",
        price: "$ 9.00",
        oldPrice: "$ 29.99",
        popular: false,
        preOrder: false,
        used: false,
    },
    {
        name: "Boxer",
        description: "Boxer, box against the biggest stars",
        id: "8",
        image: "../images/GameHub_covers8.jpg",
        price: "$ 14.99",
        oldPrice: "",
        popular: true,
        preOrder: true,
        used: true,
    },
    {
        name: "Cyberpunk",
        description: "Cyberpunk, explore the future",
        id: "9",
        image: "../images/GameHub_covers9.jpg",
        price: "$ 29.99",
        oldPrice: "",
        popular: true,
        preOrder: true,
        used: false,
    },
    {
        name: "Forge Legend",
        description: "Forge Legend, an MMO with great fantasy elements",
        id: "10",
        image: "../images/GameHub_covers10.jpg",
        price: "$ 19.99",
        oldPrice: "",
        popular: false,
        preOrder: true,
        used: false,
    },
    
]